version: "3.8"

services:

  postgres:
    image: postgres:18
    container_name: mediassist_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8431437824
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./db/mediassist_backup.sql:/docker-entrypoint-initdb.d/mediassist_backup.sql
  backend:
    build: ./backend/backend
    container_name: mediassist_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8431437824

  frontend:
    build: ./frontend
    container_name: react-app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend